### ISSUE TITLE
ユーザに不要なキャッシュファイル等がリポジトリに含まれている

### ISSUE THREAD

**Issue by bvv-1** [hashimotoshumpei/GenoSee#1]
__pycache__ や .DS_Store は、ツールを使用するユーザの実行環境で生成されるものなので、GitHubリポジトリ等でコードを共有する際には削除するほうがよいかもしれません。

- https://www-creators.com/archives/1662
  - .gitignore の役割と Git で __pycache__ や .DS_Store を追跡しない方法
- https://github.com/github/gitignore/blob/main/Python.gitignore
  - 追加する .gitignore の例

**Comment by hashimotoshumpei** [comment]
Corrected.
