### ISSUE TITLE
--outputのパスが存在していない場合作成する？

### ISSUE THREAD

**Issue by HarukiNkmr** [hashimotoshumpei/GenoSee#10]
--outputで存在しないパスを指定するとエラーが出るので
パスが存在しない場合は作成する or エラーを出す、いずれかの処理があった方が良さそうです。
お好みですね。

https://github.com/hashimotoshumpei/GenoSee/blob/142f410abcd84a114eeb7e08f6d123ef8955d52b/GenoSee.py#L41-L42
出力先のパスを作成する場合は、プロットの前に作成する処理を入れた方が良さそうですね。

```Python
    import os
    os.makedirs(args.output, exist_ok=True)

    if args.drawing_mode == "normal": 
    # ...
```

**Comment by hashimotoshumpei** [comment]
Pending.
