### ISSUE TITLE
誤字: zisualization → visualization

### ISSUE THREAD

**Issue by bvv-1** [hashimotoshumpei/GenoSee#3]
https://github.com/hashimotoshumpei/GenoSee/blob/4593e3df190d446cb25c202d5c93afeb7988da2d/README.md?plain=1#L199

**Comment by bvv-1** [comment]
https://github.com/hashimotoshumpei/GenoSee/blob/4593e3df190d446cb25c202d5c93afeb7988da2d/README.md?plain=1#L178

**Comment by bvv-1** [comment]
https://github.com/hashimotoshumpei/GenoSee/blob/4593e3df190d446cb25c202d5c93afeb7988da2d/utilities.py#L57
is not existed → does not exist

**Comment by hashimotoshumpei** [comment]
Corrected.
