### ISSUE TITLE
出てきた画像に余白が多すぎるような…🤔

### ISSUE THREAD

**Issue by bvv-1** [hashimotoshumpei/GenoSee#4]
https://github.com/hashimotoshumpei/GenoSee/blob/4593e3df190d446cb25c202d5c93afeb7988da2d/plotting.py#L595-L596

plt.savefig(f'{output_path}/{sample_name}_{mode}_{Color_mode}.pdf', dpi=dpi, bbox_inches='tight')
plt.savefig(f'{output_path}/{sample_name}_{mode}_{Color_mode}.png', dpi=dpi, bbox_inches='tight')

これで結構すっきりします。

参考: https://pysql.tecladocode.com/section09/lectures/14_export_image_matplotlib/

それから、create_normal_plotにだけ、pdfの保存時にもdpiが設定されていますが、設定変えても反映されていないような気がします。dpi=dpiを消しちゃってもいいかもしれません。

**Comment by bvv-1** [comment]
他の関数も同様です

**Comment by hashimotoshumpei** [comment]
Corrected.
