### ISSUE TITLE
check_colnames は不要？

### ISSUE THREAD

**Issue by bvv-1** [hashimotoshumpei/GenoSee#6]
https://github.com/hashimotoshumpei/GenoSee/blob/4593e3df190d446cb25c202d5c93afeb7988da2d/GenoSee.py#L36-L40

1行で済むロジックなので、utilities.pyに切り出す必要はないように思いました。

```python
if not (len(data.columns) > 3 and all(data.columns.values[:3] == ['chr', 'marker_name', 'pos'])):
    print('\nYou have wrong column name(s)😢！')
    sys.exit(1)

data.sort_values(['chr', 'pos'], inplace=True)
```

それから、data.sort_values(['chr', 'pos'], inplace=True)はcheck_colnamesの後が良さそうです。

**Comment by bvv-1** [comment]
- data.sort_values(['chr', 'pos'], inplace=True)はcheck_colnamesの後が良さそうです。
- 'pos'がint型として読み込まれる保証はないので、data['pos'] = data['pos'].astype(int)で前処理しておくと安全だと思います。もし文字列として読み込まれると、'1' > '11' > '2'のようになります。

```python
if not (len(data.columns) > 3 and all(data.columns.values[:3] == ['chr', 'marker_name', 'pos'])):
    print('\nYou have wrong column name(s)😢！')
    sys.exit(1)

data['pos'] = data['pos'].astype(int)
data.sort_values(['chr', 'pos'], inplace=True)
```

**Comment by hashimotoshumpei** [comment]
Corrected.
