### ISSUE TITLE
Examplesの 3. Local comparison graphical genotype がコピペでは動かない

### ISSUE THREAD

**Issue by bvv-1** [hashimotoshumpei/GenoSee#7]
https://github.com/hashimotoshumpei/GenoSee/blob/4593e3df190d446cb25c202d5c93afeb7988da2d/README.md?plain=1#L140

python GenoSee.py -i xxxx.csv -o ./results -s Oryza_sativa --fill on

の文字列が混入しています。

**Comment by bvv-1** [comment]
実行結果もこうなります

[Chr1A_1000000_2000000_2-color.pdf](https://github.com/user-attachments/files/15801451/Chr1A_1000000_2000000_2-color.pdf)

**Comment by hashimotoshumpei** [comment]
Corrected.
